services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      bash -lc '(command -v gunicorn >/dev/null &&
                 exec gunicorn -w 2 -b 0.0.0.0:${PORT:-5000} app:app ||
                 exec python app.py)'
